// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: grpc.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Los mensajes que se usan como parámetros de entrada y salida de los métodos RPC.
type MovimientoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NroClienteOrigen  string `protobuf:"bytes,1,opt,name=nro_cliente_origen,json=nroClienteOrigen,proto3" json:"nro_cliente_origen,omitempty"`
	NroClienteDestino string `protobuf:"bytes,2,opt,name=nro_cliente_destino,json=nroClienteDestino,proto3" json:"nro_cliente_destino,omitempty"`
	Monto             string `protobuf:"bytes,3,opt,name=monto,proto3" json:"monto,omitempty"`
	Divisa            string `protobuf:"bytes,4,opt,name=divisa,proto3" json:"divisa,omitempty"`
	TipoOperacion     string `protobuf:"bytes,5,opt,name=tipo_operacion,json=tipoOperacion,proto3" json:"tipo_operacion,omitempty"`
}

func (x *MovimientoRequest) Reset() {
	*x = MovimientoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovimientoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovimientoRequest) ProtoMessage() {}

func (x *MovimientoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovimientoRequest.ProtoReflect.Descriptor instead.
func (*MovimientoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *MovimientoRequest) GetNroClienteOrigen() string {
	if x != nil {
		return x.NroClienteOrigen
	}
	return ""
}

func (x *MovimientoRequest) GetNroClienteDestino() string {
	if x != nil {
		return x.NroClienteDestino
	}
	return ""
}

func (x *MovimientoRequest) GetMonto() string {
	if x != nil {
		return x.Monto
	}
	return ""
}

func (x *MovimientoRequest) GetDivisa() string {
	if x != nil {
		return x.Divisa
	}
	return ""
}

func (x *MovimientoRequest) GetTipoOperacion() string {
	if x != nil {
		return x.TipoOperacion
	}
	return ""
}

type MovimientoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensaje string `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *MovimientoResponse) Reset() {
	*x = MovimientoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovimientoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovimientoResponse) ProtoMessage() {}

func (x *MovimientoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovimientoResponse.ProtoReflect.Descriptor instead.
func (*MovimientoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *MovimientoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_grpc_proto protoreflect.FileDescriptor

var file_grpc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72,
	0x70, 0x63, 0x22, 0xc6, 0x01, 0x0a, 0x11, 0x4d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x72, 0x6f, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x72, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65,
	0x4f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x72, 0x6f, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x6e, 0x72, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x69, 0x76, 0x69, 0x73, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69,
	0x76, 0x69, 0x73, 0x61, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x69, 0x70, 0x6f, 0x5f, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x69,
	0x70, 0x6f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x2e, 0x0a, 0x12, 0x4d,
	0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x32, 0x57, 0x0a, 0x0b, 0x4d,
	0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x73, 0x12, 0x48, 0x0a, 0x11, 0x52, 0x65,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x72, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12,
	0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x33, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_rawDescData = file_grpc_proto_rawDesc
)

func file_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_rawDescData)
	})
	return file_grpc_proto_rawDescData
}

var file_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_proto_goTypes = []interface{}{
	(*MovimientoRequest)(nil),  // 0: grpc.MovimientoRequest
	(*MovimientoResponse)(nil), // 1: grpc.MovimientoResponse
}
var file_grpc_proto_depIdxs = []int32{
	0, // 0: grpc.Movimientos.RealizarOperacion:input_type -> grpc.MovimientoRequest
	1, // 1: grpc.Movimientos.RealizarOperacion:output_type -> grpc.MovimientoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_init() }
func file_grpc_proto_init() {
	if File_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovimientoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovimientoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto = out.File
	file_grpc_proto_rawDesc = nil
	file_grpc_proto_goTypes = nil
	file_grpc_proto_depIdxs = nil
}
